# Generated by Django 6.0.7 on 2026-07-27 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('business_type', models.CharField(choices=[('building_materials', 'Building materials'), ('boutique', 'Boutique')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('inventory_clerk', 'Inventory clerk')], default='cashier', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('business__name', 'user__email'),
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'status'], name='businesses__owner_i_423ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type', 'status'], name='businesses__busines_b5bc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['business', 'is_active'], name='businesses__busines_89c58b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['user', 'is_active'], name='businesses__user_id_4ec985_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['business', 'role'], name='businesses__busines_80e565_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_user_membership_per_business'),
        ),
    ]
