# Generated by Django 6.0.7 on 2026-07-28 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=12, validators=[django.core.validators.RegexValidator(message='Use only letters, numbers and hyphens for document prefixes.', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AddField(
            model_name='business',
            name='receipt_prefix',
            field=models.CharField(default='RCT', max_length=12, validators=[django.core.validators.RegexValidator(message='Use only letters, numbers and hyphens for document prefixes.', regex='^[A-Za-z0-9-]+$')]),
        ),
    ]
