# Generated by Django 6.0.7 on 2026-07-31 22:09

import businesses.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_invoice_prefix_business_receipt_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Free trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateTimeField(default=businesses.models.default_trial_ends_at),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
