# Generated by Django 6.0.7 on 2026-08-02 12:38

import businesses.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_subscription_ends_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_by_email', models.EmailField(max_length=254)),
                ('initiated_by_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=10)),
                ('amount_subunit', models.PositiveIntegerField(default=9900)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('duration_days', models.PositiveSmallIntegerField(default=40)),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=30)),
                ('reference', models.CharField(default=businesses.models.generate_subscription_payment_reference, editable=False, max_length=80, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=80)),
                ('provider_status', models.CharField(blank=True, max_length=40)),
                ('channel', models.CharField(blank=True, max_length=40)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('access_code', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='businesses.business')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'status'], name='businesses__busines_49faf5_idx'), models.Index(fields=['business', 'created_at'], name='businesses__busines_279486_idx'), models.Index(fields=['status', 'created_at'], name='businesses__status_13c6d4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='subscription_payment_amount_above_zero'), models.CheckConstraint(condition=models.Q(('amount_subunit__gt', 0)), name='subscription_payment_subunit_above_zero'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='subscription_payment_duration_above_zero'), models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('gateway', 'provider_transaction_id'), name='unique_subscription_provider_transaction')],
            },
        ),
    ]
