# Generated by Django 6.0.7 on 2026-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='vat_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_registration_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
