# Generated by Django 6.0.7 on 2026-09-07 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_businesspaymentaccount_paystack_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=40)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stockflow_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_main', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BranchAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_assignments', to='businesses.branch')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('branch__name', 'membership__user__email'),
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'is_active'], name='businesses__busines_569a76_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'name'], name='businesses__busines_3f19d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_branch_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('business',), name='unique_main_branch_per_business'),
        ),
        migrations.AddIndex(
            model_name='branchaccess',
            index=models.Index(fields=['branch', 'is_active'], name='businesses__branch__957a21_idx'),
        ),
        migrations.AddIndex(
            model_name='branchaccess',
            index=models.Index(fields=['membership', 'is_active'], name='businesses__members_324947_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchaccess',
            constraint=models.UniqueConstraint(fields=('branch', 'membership'), name='unique_membership_branch_access'),
        ),
    ]
