"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads development secrets locally and deployment variables in production.
load_dotenv(BASE_DIR / ".env")


def get_required_env(name):
    # Stops startup when a required secret is missing.
    value = os.getenv(name, "").strip()

    if not value:
        raise ImproperlyConfigured(
            f"The required environment variable {name} is missing."
        )

    return value


def get_env_bool(name, default=False):
    # Converts common environment values into a Python boolean.
    value = os.getenv(name)

    if value is None:
        return default

    return value.strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def get_env_list(name, default=""):
    # Converts a comma-separated environment variable into a clean list.
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = get_env_list(
    "DJANGO_ALLOWED_HOSTS",
    default="127.0.0.1,localhost",
)

# Provider-neutral payment settings. Real credentials stay in environment variables.
PAYMENT_GATEWAY = os.getenv("PAYMENT_GATEWAY", "").strip().lower()
PAYMENT_GATEWAY_SECRET_KEY = os.getenv(
    "PAYMENT_GATEWAY_SECRET_KEY",
    "",
).strip()
PAYMENT_GATEWAY_PUBLIC_KEY = os.getenv(
    "PAYMENT_GATEWAY_PUBLIC_KEY",
    "",
).strip()
PAYMENT_WEBHOOK_SECRET = os.getenv(
    "PAYMENT_WEBHOOK_SECRET",
    "",
).strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party applications.
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # Local applications.
    'accounts',
    'businesses',
    'inventory',
    'customers',
    'sales',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Uses the project-specific email-based user model.
AUTH_USER_MODEL = "accounts.User"

# Allows the local Vite frontend to call the Django API.
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

# Uses JWT authentication for protected API endpoints.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Limits anonymous and authenticated API abuse across StockFlow.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    # Keeps authentication endpoints stricter than ordinary API traffic.
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_RATE_ANON", "100/hour"),
        "user": os.getenv("THROTTLE_RATE_USER", "1000/hour"),
        "auth_login": os.getenv("THROTTLE_RATE_LOGIN", "10/min"),
        "auth_register": os.getenv("THROTTLE_RATE_REGISTER", "5/hour"),
        "auth_refresh": os.getenv("THROTTLE_RATE_REFRESH", "30/min"),
        "auth_logout": os.getenv("THROTTLE_RATE_LOGOUT", "20/min"),
    },
}

# Keeps access tokens short-lived while allowing secure refresh rotation.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Allows StockFlow's protected retry header through CORS preflight.
from corsheaders.defaults import default_headers as cors_default_headers

_existing_cors_allow_headers = globals().get(
    "CORS_ALLOW_HEADERS",
    cors_default_headers,
)
CORS_ALLOW_HEADERS = tuple(
    dict.fromkeys(
        (
            *_existing_cors_allow_headers,
            "idempotency-key",
        )
    )
)
