import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("integrations", "0002_messaging_foundation")]

    operations = [
        migrations.CreateModel(
            name="ApiCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("key_prefix", models.CharField(max_length=40, unique=True)),
                ("secret_hash", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_credentials", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_stockflow_api_credentials", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("name", "created_at")},
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=500)),
                ("events", models.JSONField(blank=True, default=list)),
                ("secret_salt", models.CharField(default=uuid.uuid4, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhook_endpoints", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_webhook_endpoints", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("name", "created_at")},
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=60)),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhook_events", to="businesses.business")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AccountingConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("quickbooks", "QuickBooks Online"), ("xero", "Xero")], max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("disconnected", "Disconnected"), ("connected", "Connected"), ("error", "Error")], default="disconnected", max_length=20)),
                ("external_company_id", models.CharField(blank=True, max_length=160)),
                ("external_company_name", models.CharField(blank=True, max_length=180)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accounting_connections", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_accounting_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("provider", "name")},
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=20)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("response_code", models.PositiveIntegerField(default=0)),
                ("response_summary", models.TextField(blank=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="integrations.webhookendpoint")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="integrations.webhookevent")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="AccountingExternalReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=40)),
                ("stockflow_id", models.CharField(max_length=80)),
                ("external_id", models.CharField(max_length=160)),
                ("sync_hash", models.CharField(blank=True, max_length=64)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_references", to="integrations.accountingconnection")),
            ],
        ),
        migrations.CreateModel(
            name="AccountingSyncRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="running", max_length=20)),
                ("entity_type", models.CharField(blank=True, max_length=40)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("synced_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_runs", to="integrations.accountingconnection")),
            ],
            options={"ordering": ("-started_at",)},
        ),
        migrations.AddConstraint(model_name="webhookdelivery", constraint=models.UniqueConstraint(fields=("event", "endpoint"), name="uniq_integ_webhook_event_endpoint")),
        migrations.AddConstraint(model_name="accountingconnection", constraint=models.UniqueConstraint(fields=("business", "provider", "name"), name="uniq_integ_account_conn_name")),
        migrations.AddConstraint(model_name="accountingexternalreference", constraint=models.UniqueConstraint(fields=("connection", "entity_type", "stockflow_id"), name="uniq_integ_acct_stockflow_ref")),
        migrations.AddConstraint(model_name="accountingexternalreference", constraint=models.UniqueConstraint(fields=("connection", "entity_type", "external_id"), name="uniq_integ_acct_external_ref")),
        migrations.AddIndex(model_name="apicredential", index=models.Index(fields=["business", "is_active"], name="integ_api_bus_active_idx")),
        migrations.AddIndex(model_name="webhookendpoint", index=models.Index(fields=["business", "is_active"], name="integ_hook_bus_active_idx")),
        migrations.AddIndex(model_name="webhookevent", index=models.Index(fields=["business", "created_at"], name="integ_event_bus_created_idx")),
        migrations.AddIndex(model_name="webhookdelivery", index=models.Index(fields=["status", "next_attempt_at"], name="integ_delivery_due_idx")),
        migrations.AddIndex(model_name="accountingsyncrun", index=models.Index(fields=["connection", "started_at"], name="integ_sync_conn_start_idx")),
    ]
