import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_public_api_webhooks_accounting_foundation"),
        ("businesses", "0009_branch_branchaccess_and_more"),
        ("inventory", "0005_restockpurchase_branch_stockmovement_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("shopify", "Shopify"), ("woocommerce", "WooCommerce")], max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("shop_url", models.URLField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("disconnected", "Disconnected"), ("connected", "Connected"), ("error", "Error")], default="disconnected", max_length=20)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commerce_connections", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_commerce_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("provider", "name")},
        ),
        migrations.CreateModel(
            name="CommerceSyncRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("direction", models.CharField(choices=[("outbound", "StockFlow to commerce"), ("inbound", "Commerce to StockFlow")], max_length=20)),
                ("entity_type", models.CharField(max_length=40)),
                ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="running", max_length=20)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("synced_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sync_runs", to="integrations.commerceconnection")),
            ],
            options={"ordering": ("-started_at",)},
        ),
        migrations.CreateModel(
            name="CommerceExternalReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=40)),
                ("stockflow_id", models.CharField(max_length=80)),
                ("external_id", models.CharField(max_length=180)),
                ("sync_hash", models.CharField(blank=True, max_length=64)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_references", to="integrations.commerceconnection")),
            ],
        ),
        migrations.CreateModel(
            name="ExternalCommerceOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_order_id", models.CharField(max_length=180)),
                ("external_order_number", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("staged", "Staged"), ("ready", "Ready for review"), ("blocked", "Blocked by missing mappings"), ("rejected", "Rejected")], default="staged", max_length=20)),
                ("payment_status", models.CharField(choices=[("unknown", "Unknown"), ("unpaid", "Unpaid"), ("partially_paid", "Partially paid"), ("paid", "Paid"), ("refunded", "Refunded")], default="unknown", max_length=30)),
                ("currency", models.CharField(default="GHS", max_length=10)),
                ("customer_name", models.CharField(blank=True, max_length=180)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=40)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("shipping_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("source_hash", models.CharField(max_length=64)),
                ("source_summary", models.JSONField(blank=True, default=dict)),
                ("staged_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_commerce_orders", to="businesses.business")),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="external_orders", to="integrations.commerceconnection")),
                ("staged_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staged_external_commerce_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-staged_at",)},
        ),
        migrations.CreateModel(
            name="ExternalCommerceOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_item_id", models.CharField(max_length=180)),
                ("external_product_id", models.CharField(blank=True, max_length=180)),
                ("name", models.CharField(max_length=220)),
                ("sku", models.CharField(blank=True, max_length=120)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="integrations.externalcommerceorder")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="external_commerce_order_items", to="inventory.product")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="SupplierPurchaseOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("po_number", models.CharField(max_length=40, unique=True)),
                ("supplier_reference", models.CharField(blank=True, max_length=120)),
                ("order_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("issued", "Issued"), ("partially_received", "Partially received"), ("received", "Received"), ("cancelled", "Cancelled")], default="draft", max_length=30)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_purchase_orders", to="businesses.branch")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="supplier_purchase_orders", to="businesses.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_supplier_purchase_orders", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="inventory.supplier")),
            ],
            options={"ordering": ("-order_date", "-created_at")},
        ),
        migrations.CreateModel(
            name="SupplierPurchaseOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=220)),
                ("sku", models.CharField(blank=True, max_length=120)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("quantity_ordered", models.PositiveIntegerField()),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_purchase_order_items", to="inventory.product")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="integrations.supplierpurchaseorder")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="SupplierPurchaseOrderReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("restock_purchase_id", models.CharField(max_length=80)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="receipts", to="integrations.supplierpurchaseorder")),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_supplier_purchase_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("received_at",)},
        ),
        migrations.AddConstraint(model_name="commerceconnection", constraint=models.UniqueConstraint(fields=("business", "provider", "name"), name="uniq_integ_commerce_conn_name")),
        migrations.AddConstraint(model_name="commerceexternalreference", constraint=models.UniqueConstraint(fields=("connection", "entity_type", "stockflow_id"), name="uniq_integ_com_stockflow_ref")),
        migrations.AddConstraint(model_name="commerceexternalreference", constraint=models.UniqueConstraint(fields=("connection", "entity_type", "external_id"), name="uniq_integ_com_external_ref")),
        migrations.AddConstraint(model_name="externalcommerceorder", constraint=models.UniqueConstraint(fields=("connection", "external_order_id"), name="uniq_integ_com_external_order")),
        migrations.AddConstraint(model_name="externalcommerceorderitem", constraint=models.UniqueConstraint(fields=("order", "external_item_id"), name="uniq_integ_com_order_item")),
        migrations.AddConstraint(model_name="supplierpurchaseorderitem", constraint=models.UniqueConstraint(fields=("purchase_order", "product"), name="uniq_integ_spo_product")),
        migrations.AddConstraint(model_name="supplierpurchaseorderreceipt", constraint=models.UniqueConstraint(fields=("purchase_order", "idempotency_key"), name="uniq_integ_spo_receipt_key")),
        migrations.AddIndex(model_name="commerceconnection", index=models.Index(fields=["business", "status"], name="integ_com_bus_status_idx")),
        migrations.AddIndex(model_name="commerceexternalreference", index=models.Index(fields=["connection", "entity_type"], name="integ_com_ref_type_idx")),
        migrations.AddIndex(model_name="commercesyncrun", index=models.Index(fields=["connection", "started_at"], name="integ_com_sync_start_idx")),
        migrations.AddIndex(model_name="externalcommerceorder", index=models.Index(fields=["business", "status", "staged_at"], name="integ_com_order_status_idx")),
        migrations.AddIndex(model_name="supplierpurchaseorder", index=models.Index(fields=["business", "status", "order_date"], name="integ_spo_bus_status_idx")),
        migrations.AddIndex(model_name="supplierpurchaseorder", index=models.Index(fields=["supplier", "order_date"], name="integ_spo_supplier_idx")),
    ]
