# Generated by Django 6.0.7 on 2026-09-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_notificationread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredential',
            name='category',
            field=models.CharField(choices=[('accounting', 'Accounting'), ('commerce', 'Commerce'), ('messaging', 'Messaging'), ('social', 'Social publishing')], max_length=20),
        ),
    ]
