# Generated by Django 6.0.7 on 2026-09-10 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0009_branch_branchaccess_and_more'),
        ('inventory', '0005_restockpurchase_branch_stockmovement_branch_and_more'),
        ('sales', '0009_sale_branch_sale_sales_sale_busines_f62354_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('introduction', models.CharField(blank=True, max_length=500)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storefronts', to='businesses.branch')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='StorefrontOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_note', models.CharField(blank=True, max_length=1000)),
                ('currency', models.CharField(choices=[('GHS', 'Ghana cedi')], default='GHS', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storefront_orders', to='businesses.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_storefront_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storefront_order', to='sales.sale')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='storefront.storefront')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorefrontOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.storefrontorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storefront_order_items', to='inventory.product')),
            ],
            options={
                'ordering': ('product_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StorefrontListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storefront_listings', to='inventory.product')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='storefront.storefront')),
            ],
            options={
                'ordering': ('product__name',),
                'indexes': [models.Index(fields=['storefront', 'is_published'], name='storefront__storefr_473e68_idx')],
                'constraints': [models.UniqueConstraint(fields=('storefront', 'product'), name='uniq_storefront_listing_product')],
            },
        ),
        migrations.AddIndex(
            model_name='storefrontorder',
            index=models.Index(fields=['storefront', 'status', 'created_at'], name='storefront__storefr_dce192_idx'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorder',
            constraint=models.UniqueConstraint(fields=('storefront', 'idempotency_key'), name='uniq_storefront_order_request'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='storefront_order_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('sale__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('sale__isnull', True), ('status__in', ['pending', 'cancelled'])), _connector='OR'), name='storefront_order_sale_state'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='uniq_storefront_order_product'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='storefront_item_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='storefront_item_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='storefrontorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='storefront_item_total_nonneg'),
        ),
    ]
