# Generated by Django 6.0.7 on 2026-09-10 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('shop_visit', 'Shop visit'), ('product_view', 'Product view'), ('product_search', 'Product search'), ('cart_add', 'Add to cart'), ('recommendation_shown', 'Recommendation shown'), ('recommendation_click', 'Recommendation clicked')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='storefront.storefrontlisting')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='storefront.storefront')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['storefront', 'event_type', 'created_at'], name='storefront__storefr_194dc7_idx'), models.Index(fields=['listing', 'event_type', 'created_at'], name='storefront__listing_1b5384_idx'), models.Index(fields=['storefront', 'session_id', 'created_at'], name='storefront__storefr_72f351_idx')],
                'constraints': [models.UniqueConstraint(fields=('storefront', 'event_id'), name='uniq_storefront_activity_event')],
            },
        ),
    ]
