# Generated by Django 6.0.7 on 2026-09-10 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_storefrontactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat')], max_length=20)),
                ('auto_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_channels', to='storefront.storefront')),
            ],
            options={
                'ordering': ('platform',),
            },
        ),
        migrations.CreateModel(
            name='SocialPublishingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_connection', 'Pending connection'), ('cancelled', 'Cancelled')], default='pending_connection', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='storefront.socialchannel')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_jobs', to='storefront.storefrontlisting')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='socialchannel',
            constraint=models.UniqueConstraint(fields=('storefront', 'platform'), name='sf_social_channel_unique'),
        ),
        migrations.AddIndex(
            model_name='socialpublishingjob',
            index=models.Index(fields=['channel', 'status'], name='sf_social_job_status'),
        ),
        migrations.AddConstraint(
            model_name='socialpublishingjob',
            constraint=models.UniqueConstraint(fields=('channel', 'listing'), name='sf_social_job_unique'),
        ),
    ]
