# Generated by Django 6.0.7 on 2026-09-15 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_storefront_whatsapp_enquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Outcome unknown')], max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('provider_post_id', models.CharField(blank=True, max_length=180)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='storefront.socialpublishingjob')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['job', 'status'], name='sf_social_delivery_status')],
                'constraints': [models.UniqueConstraint(fields=('job', 'fingerprint'), name='sf_social_delivery_version_unique')],
            },
        ),
    ]
