# Generated by Django 6.0.7 on 2026-09-23 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_branch_branchaccess_and_more'),
        ('inventory', '0007_productvideo'),
        ('storefront', '0007_socialauthorizationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_version', models.UUIDField()),
                ('account_id', models.CharField(max_length=180)),
                ('account_name', models.CharField(max_length=180)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('publish_id', models.CharField(blank=True, max_length=180)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('post_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvideo')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
