from django.urls import path

from .views import (
    BusinessIntelligenceAnalystAPIView,
    BusinessIntelligenceBranchesAPIView,
    BusinessIntelligenceAutomationEventAPIView,
    BusinessIntelligenceAutomationRuleCollectionAPIView,
    BusinessIntelligenceAutomationRuleDetailAPIView,
    BusinessIntelligenceAutomationRunAPIView,
    BusinessIntelligenceAutomationRunNowAPIView,
    BusinessIntelligenceForecastAPIView,
    BusinessIntelligenceOverviewAPIView,
    BusinessIntelligenceRecommendationAPIView,
    BusinessIntelligenceReportCollectionAPIView,
    BusinessIntelligenceReportDetailAPIView,
)


urlpatterns = [
    path(
        "businesses/<uuid:business_id>/intelligence/branches/",
        BusinessIntelligenceBranchesAPIView.as_view(),
        name="business-intelligence-branches",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/overview/",
        BusinessIntelligenceOverviewAPIView.as_view(),
        name="business-intelligence-overview",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/forecasts/",
        BusinessIntelligenceForecastAPIView.as_view(),
        name="business-intelligence-forecast",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/recommendations/",
        BusinessIntelligenceRecommendationAPIView.as_view(),
        name="business-intelligence-recommendations",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/analyst/",
        BusinessIntelligenceAnalystAPIView.as_view(),
        name="business-intelligence-analyst",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/reports/",
        BusinessIntelligenceReportCollectionAPIView.as_view(),
        name="business-intelligence-reports",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/reports/"
        "<uuid:report_id>/",
        BusinessIntelligenceReportDetailAPIView.as_view(),
        name="business-intelligence-report-detail",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/automation/rules/",
        BusinessIntelligenceAutomationRuleCollectionAPIView.as_view(),
        name="business-intelligence-automation-rules",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/automation/rules/"
        "<uuid:rule_id>/",
        BusinessIntelligenceAutomationRuleDetailAPIView.as_view(),
        name="business-intelligence-automation-rule-detail",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/automation/rules/"
        "<uuid:rule_id>/run/",
        BusinessIntelligenceAutomationRunNowAPIView.as_view(),
        name="business-intelligence-automation-run-now",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/automation/events/",
        BusinessIntelligenceAutomationEventAPIView.as_view(),
        name="business-intelligence-automation-events",
    ),
    path(
        "businesses/<uuid:business_id>/intelligence/automation/runs/",
        BusinessIntelligenceAutomationRunAPIView.as_view(),
        name="business-intelligence-automation-runs",
    ),
]
