# Generated by Django 6.0.7 on 2026-07-28 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['business', 'is_active'], name='customers_c_busines_184bcb_idx'), models.Index(fields=['business', 'name'], name='customers_c_busines_67b0d8_idx'), models.Index(fields=['business', 'phone'], name='customers_c_busines_fc2d10_idx'), models.Index(fields=['business', 'outstanding_balance'], name='customers_c_busines_41267b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outstanding_balance__gte', 0)), name='customer_outstanding_balance_not_negative'), models.CheckConstraint(condition=models.Q(('total_purchases__gte', 0)), name='customer_total_purchases_not_negative')],
            },
        ),
    ]
