# Generated by Django 6.0.7 on 2026-09-05 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0008_businesspaymentaccount_paystack_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('overview', 'Overview')], default='overview', max_length=30)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_snapshots', to='businesses.business')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('performance', 'Performance'), ('inventory', 'Inventory'), ('debt', 'Debt'), ('margin', 'Margin'), ('anomaly', 'Anomaly')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('attention', 'Needs attention'), ('high', 'High priority')], default='info', max_length=20)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_insights', to='businesses.business')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='intelligence.intelligencesnapshot')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon_days', models.PositiveSmallIntegerField(choices=[(7, '7 days'), (30, '30 days'), (90, '90 days')])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('algorithm', models.CharField(max_length=80)),
                ('algorithm_version', models.CharField(blank=True, max_length=40)),
                ('history_start', models.DateField(blank=True, null=True)),
                ('history_end', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='businesses.business')),
            ],
            options={
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['business', 'horizon_days', 'generated_at'], name='intelligenc_busines_8d6356_idx'), models.Index(fields=['business', 'generated_at'], name='intelligenc_busines_50d245_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['business', 'snapshot_type', 'generated_at'], name='intelligenc_busines_8bc9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencesnapshot',
            index=models.Index(fields=['business', 'generated_at'], name='intelligenc_busines_45018d_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['business', 'status', 'generated_at'], name='intelligenc_busines_12eb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinsight',
            index=models.Index(fields=['business', 'insight_type', 'generated_at'], name='intelligenc_busines_a7099a_idx'),
        ),
    ]
