# Generated by Django 6.0.7 on 2026-07-27 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('standard', 'Standard product'), ('tile', 'Tile product'), ('fashion', 'Boutique product')], default='standard', max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('bag', 'Bag'), ('pack', 'Pack'), ('bundle', 'Bundle'), ('length', 'Length'), ('litre', 'Litre'), ('kilogram', 'Kilogram')], default='piece', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_level', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('design_code', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=120)),
                ('batch_number', models.CharField(blank=True, max_length=120)),
                ('pieces_per_box', models.PositiveIntegerField(default=0)),
                ('sqm_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loose_pieces', models.PositiveIntegerField(default=0)),
                ('style_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['business', 'is_active'], name='inventory_p_busines_dc2763_idx'), models.Index(fields=['business', 'product_type'], name='inventory_p_busines_e1686b_idx'), models.Index(fields=['business', 'category'], name='inventory_p_busines_821368_idx'), models.Index(fields=['business', 'name'], name='inventory_p_busines_c181c4_idx'), models.Index(fields=['business', 'design_code'], name='inventory_p_busines_e77620_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'sku'), name='unique_product_sku_per_business')],
            },
        ),
    ]
