# Generated by Django 6.0.7 on 2026-07-28 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('unit', models.CharField(max_length=20)),
                ('movement_type', models.CharField(choices=[('stock_in', 'New stock received'), ('adjustment', 'Manual correction'), ('damage', 'Damaged stock'), ('return', 'Customer return'), ('sale', 'Sale')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'created_at'], name='inventory_s_busines_bc0fa5_idx'), models.Index(fields=['business', 'movement_type'], name='inventory_s_busines_a51983_idx'), models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx')],
            },
        ),
    ]
