# Generated by Django 6.0.7 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_invoice_prefix_business_receipt_prefix'),
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_stock__lte', models.F('stock'))), name='reserved_stock_cannot_exceed_stock'),
        ),
    ]
