# Generated by Django 6.0.7 on 2026-09-04 16:26

import django.db.models.deletion
import django.utils.timezone
import inventory.restock_models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_businesspaymentaccount_paystack_payout'),
        ('inventory', '0003_product_reserved_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='businesses.business')),
            ],
            options={
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RestockPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(default=inventory.restock_models.generate_restock_number, editable=False, max_length=32, unique=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_purchases', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restock_purchases', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_purchases', to='inventory.supplier')),
            ],
            options={
                'ordering': ('-purchase_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RestockPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank transfer')], default='cash', max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_payments', to='businesses.business')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_restock_payments', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.restockpurchase')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='restock_payment_amount_above_zero')],
            },
        ),
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_items', to='inventory.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.restockpurchase')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='restock_item_quantity_above_zero'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='restock_item_unit_cost_not_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'is_active'], name='inventory_s_busines_47c58a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'name'], name='inventory_s_busines_d103e7_idx'),
        ),
        migrations.AddIndex(
            model_name='restockpurchase',
            index=models.Index(fields=['business', 'purchase_date'], name='inventory_r_busines_eb4110_idx'),
        ),
        migrations.AddIndex(
            model_name='restockpurchase',
            index=models.Index(fields=['business', 'payment_status'], name='inventory_r_busines_662f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='restockpurchase',
            index=models.Index(fields=['supplier', 'purchase_date'], name='inventory_r_supplie_b4a348_idx'),
        ),
        migrations.AddConstraint(
            model_name='restockpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='restock_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='restockpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='restock_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='restockpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total_amount'))), name='restock_paid_not_above_total'),
        ),
    ]
