# Generated by Django 6.0.7 on 2026-09-07 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_branch_branchaccess_and_more'),
        ('inventory', '0004_supplier_restockpurchase_restockpayment_restockitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restockpurchase',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restock_purchases', to='businesses.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='businesses.branch'),
        ),
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='businesses.branch')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='businesses.branch')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BranchTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_transfer_items', to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.branchtransfer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='businesses.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventories', to='inventory.product')),
            ],
            options={
                'ordering': ('branch__name', 'product__name'),
                'indexes': [models.Index(fields=['branch', 'product'], name='inventory_b_branch__677719_idx'), models.Index(fields=['branch', 'stock'], name='inventory_b_branch__d7a4ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='unique_product_inventory_per_branch'), models.CheckConstraint(condition=models.Q(('reserved_stock__lte', models.F('stock'))), name='branch_reserved_stock_cannot_exceed_stock')],
            },
        ),
        migrations.CreateModel(
            name='BranchStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('movement_type', models.CharField(choices=[('opening_stock', 'Opening stock'), ('stock_in', 'Stock received'), ('adjustment', 'Manual correction'), ('damage', 'Damaged stock'), ('return', 'Customer return'), ('sale', 'Sale'), ('reserve', 'Payment reservation'), ('release', 'Reservation released'), ('transfer_in', 'Branch transfer in'), ('transfer_out', 'Branch transfer out')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('previous_reserved_stock', models.PositiveIntegerField(default=0)),
                ('new_reserved_stock', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('created_by_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock_movements', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock_movements', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock_movements', to='inventory.product')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_movement', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['branch', 'created_at'], name='inventory_b_branch__239b2e_idx'), models.Index(fields=['branch', 'movement_type'], name='inventory_b_branch__f3e06e_idx'), models.Index(fields=['product', 'created_at'], name='inventory_b_product_a68e1c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['business', 'created_at'], name='inventory_b_busines_1da986_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['source_branch', 'created_at'], name='inventory_b_source__a7a2be_idx'),
        ),
        migrations.AddIndex(
            model_name='branchtransfer',
            index=models.Index(fields=['destination_branch', 'created_at'], name='inventory_b_destina_70013a_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchtransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='unique_product_per_branch_transfer'),
        ),
        migrations.AddConstraint(
            model_name='branchtransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='branch_transfer_quantity_above_zero'),
        ),
    ]
