# Generated by Django 6.0.7 on 2026-09-17

import django.db.models.deletion
import inventory.photo_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(max_length=255, storage=inventory.photo_storage.product_photo_storage, upload_to='product-videos/')),
                ('version', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content_type', models.CharField(default='video/mp4', max_length=80)),
                ('extension', models.CharField(default='mp4', max_length=8)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_video', to='inventory.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
