# Generated by Django 5.2.17 on 2026-09-28 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(db_index=True, default='info', max_length=12)),
                ('action', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=240)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('business_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('route', models.CharField(blank=True, max_length=240)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('source', models.CharField(default='application', max_length=32)),
                ('peer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('details', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
                'indexes': [models.Index(fields=['severity', '-occurred_at'], name='pe_severity_time')],
            },
        ),
    ]
