# Generated by Django 5.2.17 on 2026-09-29 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_events', '0002_import_admin_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='application', max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('reporter_id', models.CharField(blank=True, max_length=64)),
                ('business_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_events.platformevent')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
