# Generated by Django 6.0.7 on 2026-07-28 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_invoice_prefix_business_receipt_prefix'),
        ('customers', '0001_initial'),
        ('inventory', '0003_product_reserved_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_sale_number', models.PositiveBigIntegerField(default=1)),
                ('next_invoice_number', models.PositiveBigIntegerField(default=1)),
                ('next_receipt_number', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequence', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='Walk-in customer', max_length=180)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('sale_number', models.CharField(max_length=40)),
                ('invoice_number', models.CharField(max_length=40)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank transfer'), ('credit', 'Credit or part payment')], max_length=30)),
                ('status', models.CharField(choices=[('pending_payment', 'Payment pending'), ('completed', 'Completed'), ('partially_paid', 'Partially paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending_payment', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cashier_name', models.CharField(max_length=150)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='businesses.business')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('sale_payment', 'Sale payment'), ('debt_payment', 'Customer debt payment'), ('refund', 'Refund')], default='sale_payment', max_length=30)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank transfer')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mobile_money_network', models.CharField(blank=True, max_length=40)),
                ('mobile_money_number', models.CharField(blank=True, max_length=30)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('reference', models.CharField(blank=True, max_length=180)),
                ('note', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_by_name', models.CharField(max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=100)),
                ('design_code', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'created_at'], name='sales_sale_busines_1e4819_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'status'], name='sales_sale_busines_1c85e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'payment_method'], name='sales_sale_busines_2856fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'created_at'], name='sales_sale_custome_dd8d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'sale_number'), name='unique_sale_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='unique_invoice_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sale_subtotal_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='sale_discount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='sale_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='sale_amount_paid_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_balance__gte', 0)), name='sale_outstanding_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('subtotal'))), name='sale_discount_not_above_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total'))), name='sale_amount_paid_not_above_total'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'created_at'], name='sales_payme_busines_f24521_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'status'], name='sales_payme_busines_da43b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'method'], name='sales_payme_busines_e0fe31_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'created_at'], name='sales_payme_sale_id_eb26d1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'created_at'], name='sales_payme_custome_6840d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_above_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number', ''), _negated=True), fields=('business', 'receipt_number'), name='unique_receipt_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('business', 'idempotency_key'), name='unique_payment_idempotency_per_business'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('gateway', 'provider_reference'), name='unique_provider_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sales_salei_product_f87493_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_above_zero'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_unit_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='sale_item_cost_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='sale_item_line_total_not_negative'),
        ),
    ]
