# Generated by Django 6.0.2 on 2026-07-30 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_invoice_prefix_business_receipt_prefix'),
        ('sales', '0002_sale_idempotency_key_sale_reservation_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsequence',
            name='next_waybill_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waybill_number', models.CharField(max_length=40)),
                ('recipient_name', models.CharField(max_length=180)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('delivery_address', models.TextField()),
                ('dispatch_date', models.DateField()),
                ('driver_name', models.CharField(blank=True, max_length=180)),
                ('vehicle_number', models.CharField(blank=True, max_length=80)),
                ('delivery_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waybills', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waybill', to='sales.sale')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['business', 'created_at'], name='sales_waybi_busines_13865b_idx'), models.Index(fields=['business', 'status'], name='sales_waybi_busines_a45c4f_idx'), models.Index(fields=['business', 'dispatch_date'], name='sales_waybi_busines_b68ae7_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'waybill_number'), name='unique_waybill_number_per_business')],
            },
        ),
    ]
