# Generated by Django 6.0.7 on 2026-08-02 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_subscriptionpayment'),
        ('customers', '0001_initial'),
        ('sales', '0003_documentsequence_next_waybill_number_waybill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_reference', ''), _negated=True), fields=('gateway', 'gateway_reference'), name='unique_gateway_payment_reference'),
        ),
    ]
