# Generated by Django 6.0.7 on 2026-08-04 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_subscriptionpayment'),
        ('customers', '0001_initial'),
        ('sales', '0004_payment_unique_gateway_payment_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtOverdueCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_percentage', models.PositiveSmallIntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%')])),
                ('principal_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_charge_required', models.DecimalField(decimal_places=2, max_digits=14)),
                ('incremental_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('applied_at',),
            },
        ),
        migrations.CreateModel(
            name='DebtReminderAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('recipient_snapshot', models.CharField(blank=True, max_length=30)),
                ('message_snapshot', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('provider_response_summary', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='DebtReminderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateField()),
                ('reminder_sequence_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scheduled_for', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_principal_at_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'debt_due_date'], name='sales_sale_busines_08535b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('debt_principal_at_due__gte', 0)), name='sale_debt_principal_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('debt_principal_at_due__lte', models.F('total'))), name='sale_debt_principal_not_above_total'),
        ),
        migrations.AddField(
            model_name='debtoverduecharge',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_overdue_charges', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='debtoverduecharge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_overdue_charges', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='debtoverduecharge',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_charges', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='debtreminderattempt',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_reminder_attempts', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='debtreminderattempt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_reminder_attempts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='debtreminderattempt',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_reminder_attempts', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='debtreminderschedule',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_reminder_schedules', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='debtreminderschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_reminder_schedules', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='debtreminderschedule',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_reminder_schedules', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='debtreminderattempt',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sales.debtreminderschedule'),
        ),
        migrations.AddIndex(
            model_name='debtoverduecharge',
            index=models.Index(fields=['business', 'applied_at'], name='sales_debto_busines_383bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='debtoverduecharge',
            index=models.Index(fields=['customer', 'applied_at'], name='sales_debto_custome_ba4efa_idx'),
        ),
        migrations.AddIndex(
            model_name='debtoverduecharge',
            index=models.Index(fields=['sale', 'tier_percentage'], name='sales_debto_sale_id_76ed18_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtoverduecharge',
            constraint=models.UniqueConstraint(fields=('sale', 'tier_percentage'), name='unique_overdue_tier_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='debtoverduecharge',
            constraint=models.CheckConstraint(condition=models.Q(('tier_percentage__in', (5, 10, 15, 20, 25, 30))), name='valid_overdue_tier_percentage'),
        ),
        migrations.AddConstraint(
            model_name='debtoverduecharge',
            constraint=models.CheckConstraint(condition=models.Q(('principal_base__gte', 0)), name='overdue_principal_base_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='debtoverduecharge',
            constraint=models.CheckConstraint(condition=models.Q(('total_charge_required__gte', 0)), name='overdue_total_charge_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='debtoverduecharge',
            constraint=models.CheckConstraint(condition=models.Q(('incremental_amount__gte', 0)), name='overdue_increment_not_negative'),
        ),
        migrations.AddIndex(
            model_name='debtreminderschedule',
            index=models.Index(fields=['business', 'scheduled_for'], name='sales_debtr_busines_377c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreminderschedule',
            index=models.Index(fields=['customer', 'scheduled_for'], name='sales_debtr_custome_cc120f_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreminderschedule',
            index=models.Index(fields=['status', 'scheduled_for'], name='sales_debtr_status_58970a_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtreminderschedule',
            constraint=models.UniqueConstraint(fields=('sale', 'scheduled_for'), name='unique_debt_reminder_schedule_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='debtreminderschedule',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_sequence_number__gt', 0)), name='debt_reminder_sequence_above_zero'),
        ),
        migrations.AddIndex(
            model_name='debtreminderattempt',
            index=models.Index(fields=['business', 'attempted_at'], name='sales_debtr_busines_d48118_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreminderattempt',
            index=models.Index(fields=['customer', 'attempted_at'], name='sales_debtr_custome_866837_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreminderattempt',
            index=models.Index(fields=['status', 'attempted_at'], name='sales_debtr_status_6e3420_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtreminderattempt',
            constraint=models.UniqueConstraint(fields=('schedule', 'attempt_number'), name='unique_debt_reminder_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='debtreminderattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='debt_reminder_attempt_above_zero'),
        ),
    ]
