# Generated by Django 6.0.7 on 2026-08-04 16:24

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_subscriptionpayment'),
        ('customers', '0001_initial'),
        ('sales', '0005_debtoverduecharge_debtreminderattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('overdue_charge_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payment_allocations', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_payment_allocations', to='customers.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_allocation', to='sales.payment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_payment_allocations', to='sales.sale')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['business', 'created_at'], name='sales_debtp_busines_4d7787_idx'), models.Index(fields=['customer', 'created_at'], name='sales_debtp_custome_9b89b6_idx'), models.Index(fields=['sale', 'created_at'], name='sales_debtp_sale_id_5ca25f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_received__gt', 0)), name='debt_allocation_amount_above_zero'), models.CheckConstraint(condition=models.Q(('overdue_charge_paid__gte', 0)), name='debt_allocation_charge_not_negative'), models.CheckConstraint(condition=models.Q(('principal_paid__gte', 0)), name='debt_allocation_principal_not_negative'), models.CheckConstraint(condition=models.Q(('amount_received', django.db.models.expressions.CombinedExpression(models.F('overdue_charge_paid'), '+', models.F('principal_paid')))), name='debt_allocation_parts_equal_amount')],
            },
        ),
    ]
