# Generated by Django 6.0.7 on 2026-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_debtpaymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receiving_account_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_id_snapshot',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_masked_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_network',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiving_account_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
