# Generated by Django 6.0.7 on 2026-09-07 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_branch_branchaccess_and_more'),
        ('customers', '0001_initial'),
        ('sales', '0008_merchantpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='businesses.branch'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'branch', 'completed_at'], name='sales_sale_busines_f62354_idx'),
        ),
    ]
