# Generated by Django 6.0.9 on 2026-10-08 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0013_paystack_modes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerSmsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('event_types', models.JSONField(default=list)),
                ('pending_phone', models.CharField(blank=True, max_length=10)),
                ('challenge', models.UUIDField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerSms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('message', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('sending', 'Submitting'), ('sent', 'Accepted by SMS provider'), ('unknown', 'Delivery unconfirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='owner_sms_business_time')],
            },
        ),
    ]
